CREATE TABLE [dbo].[EXAMPLE1]
(
[CODEMP] [int] NOT NULL IDENTITY(1, 1),
[NOMEMP] [varchar] (80) COLLATE Modern_Spanish_CI_AS NULL,
[APEEMP] [varchar] (80) COLLATE Modern_Spanish_CI_AS NULL,
[DNIEMP] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[EMAEMP] [varchar] (80) COLLATE Modern_Spanish_CI_AS NULL,
[CELEMP] [char] (9) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXAMPLE1] ADD CONSTRAINT [PK__EXAMPLE1__CF9E626FA36058BF] PRIMARY KEY CLUSTERED ([CODEMP]) ON [PRIMARY]
GO
